scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: ['exercise-app-1:9464']
        labels:
          service: 'exercise-app'
          group: 'exercise'